### ISSUE TITLE
[Action Required] Need more info to submit to ComposeLibraries.com

### ISSUE THREAD

**Issue by alexstyl** [rishadappat/ReachabilityCompose#2]
Someone (either yourself or a fan of yours) submitted your library to https://composelibraries.com/.

However, I cannot include it because your library has no **description**.

Could you also add topics with the CMP platforms you support? Ie if this is a Jetpack Compose library, simply add 'jetpack-compose'. If you support

Here is an example repo with all those in place: https://github.com/composablehorizons/compose-unstyled

When you do that, kindly let me know so that I can include your library.

If you are not interested, feel free to close this issue :)

Alex from ComposeLibraries.com

**Comment by rishadappat** [comment]
Hi @alexstyl 
The submission was done by myself. I have added the desceiption as you mentioned. Please let me know if you need more information.

**Comment by alexstyl** [comment]
Looks good. It's live on the site at https://composelibraries.com/rishadappat/ReachabilityCompose

Thanks for updating the repo :)
